#############################################################################
# Generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#  Jun 09, 2022 07:18:50 PM CDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background #000000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1280x657+288+99
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    set toptitle "STAT"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background #000000 -height 75 \
        -width 125 
    vTcl:DefineAlias "$top.fra46" "PreviousFrame" vTcl:WidgetProc "Window" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab50 \
        -activeforeground SystemButtonText -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -text {Previous Runs} 
    vTcl:DefineAlias "$site_3_0.lab50" "PreviousRunsLabel" vTcl:WidgetProc "Window" 1
    button $site_3_0.but53 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command DeletePreviousRun -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Delete 
    vTcl:DefineAlias "$site_3_0.but53" "DeleteButton" vTcl:WidgetProc "Window" 1
    button $site_3_0.but56 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command ViewPreviousRun -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text View 
    vTcl:DefineAlias "$site_3_0.but56" "ViewButton" vTcl:WidgetProc "Window" 1
    canvas $site_3_0.can57 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 432 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 430 
    vTcl:DefineAlias "$site_3_0.can57" "LogoCanvas" vTcl:WidgetProc "Window" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr58 \
        -background $vTcl(actual_gui_bg) -height 535 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 372 
    vTcl:DefineAlias "$site_3_0.scr58" "Scrolledlistbox1" vTcl:WidgetProc "Window" 1

    $site_3_0.scr58.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    button $site_3_0.but59 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command LoadPreviousRun -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Load 
    vTcl:DefineAlias "$site_3_0.but59" "LoadButton" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab61 \
        -activeforeground SystemButtonText -anchor nw -background #000000 \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -text {Logged in as: } 
    vTcl:DefineAlias "$site_3_0.lab61" "UsernameLabel" vTcl:WidgetProc "Window" 1
    button $site_3_0.but62 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command {Log Out} -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Log Out} 
    vTcl:DefineAlias "$site_3_0.but62" "LogOutButton" vTcl:WidgetProc "Window" 1
    button $site_3_0.but63 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command CreateNewRun -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text New 
    vTcl:DefineAlias "$site_3_0.but63" "NewButton" vTcl:WidgetProc "Window" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.102 -y 0 -rely 0.046 -width 0 \
        -relwidth 0.15 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.137 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.274 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can57 \
        -in $site_3_0 -x 0 -relx 0.617 -y 0 -rely 0.289 -width 0 \
        -relwidth 0.336 -height 0 -relheight 0.658 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr58 \
        -in $site_3_0 -x 0 -relx 0.039 -y 0 -rely 0.137 -width 0 \
        -relwidth 0.291 -height 0 -relheight 0.814 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.411 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.68 -y 0 -rely 0.015 -width 0 \
        -relwidth 0.222 -height 0 -relheight 0.091 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 0 -relx 0.906 -y 0 -rely 0.015 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.548 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

