#############################################################################
# Generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#  Jun 14, 2022 05:03:08 PM CDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background #000000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1280x657+288+99
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    set toptitle "STAT"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background #000000 -height 75 \
        -width 125 
    vTcl:DefineAlias "$top.fra46" "SwarmFrame" vTcl:WidgetProc "Window" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab50 \
        -activeforeground SystemButtonText -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 24 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -text {Swarm Properties} 
    vTcl:DefineAlias "$site_3_0.lab50" "SwarmPropertiesLabel" vTcl:WidgetProc "Window" 1
    button $site_3_0.but53 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command GoHome -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Back 
    vTcl:DefineAlias "$site_3_0.but53" "BackButton" vTcl:WidgetProc "Window" 1
    button $site_3_0.but56 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command GoToCheck -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Next 
    vTcl:DefineAlias "$site_3_0.but56" "NextButton" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab61 \
        -activeforeground SystemButtonText -anchor nw -background #000000 \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -text {Logged in as: } 
    vTcl:DefineAlias "$site_3_0.lab61" "UsernameLabel" vTcl:WidgetProc "Window" 1
    button $site_3_0.but62 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command {Log Out} -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Log Out} 
    vTcl:DefineAlias "$site_3_0.but62" "LogOutButton" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Population 
    vTcl:DefineAlias "$site_3_0.lab67" "PopulationLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Total swarm agents.}
    }
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Thresh Init} 
    vTcl:DefineAlias "$site_3_0.lab69" "ThreshInitLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab69 <<SetBalloon>> {
        set ::vTcl::balloon::%W {How thresholds are initialized for the agents.}
    }
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Thresh Dynamic} 
    vTcl:DefineAlias "$site_3_0.lab70" "ThreshDynamicLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab70 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Turn on dynamic thresholds and set ranges.}
    }
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Thresh Dynamic Init} 
    vTcl:DefineAlias "$site_3_0.lab71" "ThreshDynamicInitLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab71 <<SetBalloon>> {
        set ::vTcl::balloon::%W {How to initialize thresholds for modes 2 and 3 of Thresh Dynamic.}
    }
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Thresh Increase} 
    vTcl:DefineAlias "$site_3_0.lab72" "ThreshIncreaseLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab72 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Amount threshold increases when agent does not act on its task.}
    }
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Thresh Decrease} 
    vTcl:DefineAlias "$site_3_0.lab73" "ThreshDecreaseLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab73 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Amount threshold decreases when agent does act on its task.}
    }
    label $site_3_0.lab74 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Prob Check} 
    vTcl:DefineAlias "$site_3_0.lab74" "ProbCheckLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab74 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Probability that agent will stop to reconsider what task to work on.}
    }
    label $site_3_0.lab75 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Response Prob} 
    vTcl:DefineAlias "$site_3_0.lab75" "ResponseProbLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab75 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Probability that an agent will act on the task it chooses.}
    }
    entry $site_3_0.ent76 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -justify right -width 10 
    vTcl:DefineAlias "$site_3_0.ent76" "PopulationEntry" vTcl:WidgetProc "Window" 1
    entry $site_3_0.ent80 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -justify right -width 10 
    vTcl:DefineAlias "$site_3_0.ent80" "ThreshIncreaseEntry" vTcl:WidgetProc "Window" 1
    entry $site_3_0.ent81 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -justify right -width 10 
    vTcl:DefineAlias "$site_3_0.ent81" "ThreshDecreaseEntry" vTcl:WidgetProc "Window" 1
    entry $site_3_0.ent82 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -justify right -width 10 
    vTcl:DefineAlias "$site_3_0.ent82" "ProbCheckEntry" vTcl:WidgetProc "Window" 1
    entry $site_3_0.ent83 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -justify right -width 10 
    vTcl:DefineAlias "$site_3_0.ent83" "ResponseProbEntry" vTcl:WidgetProc "Window" 1
    ttk::combobox $site_3_0.tCo86 \
        -values {Random Urgent {} {} {}} \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -textvariable combobox -foreground {} -background #f2b83d \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo86" "TaskSelectionEntry" vTcl:WidgetProc "Window" 1
    entry $site_3_0.ent87 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -justify right -width 10 
    vTcl:DefineAlias "$site_3_0.ent87" "ThreshInitEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab88 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Task Selection} 
    vTcl:DefineAlias "$site_3_0.lab88" "TaskSelectionLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab88 <<SetBalloon>> {
        set ::vTcl::balloon::%W {How agent selects task if more than one task stimulus falls under the
#   agent's corresponding threshold.}
    }
    label $site_3_0.lab89 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Intensity Variation} 
    vTcl:DefineAlias "$site_3_0.lab89" "IntensityVariationLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab89 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Allows the agent to specialize in a task they choose often.}
    }
    ttk::combobox $site_3_0.tCo90 \
        -values {Off {Share Range} {Individual Range} {} {} {}} \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -textvariable combobox -foreground {} -background #f2b83d \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo90" "IntensityVariationEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab91 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Aging Min} 
    vTcl:DefineAlias "$site_3_0.lab91" "AgingMinLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab91 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Minimum amount an agent can specialize.}
    }
    entry $site_3_0.ent92 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent92" "AgingMinEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab93 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Aging Max} 
    vTcl:DefineAlias "$site_3_0.lab93" "AgingMaxLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab93 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Maximum amount an agent can specialize.}
    }
    entry $site_3_0.ent94 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent94" "AgingMaxEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab95 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Aging Up} 
    vTcl:DefineAlias "$site_3_0.lab95" "AgingUpLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab95 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Learning factor for specialization.}
    }
    entry $site_3_0.ent96 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent96" "AgingUpEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab97 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Aging Down} 
    vTcl:DefineAlias "$site_3_0.lab97" "AgingDownLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab97 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Forgetting factor for specialization.}
    }
    entry $site_3_0.ent98 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent98" "AgingDownEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab99 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Kill Number} 
    vTcl:DefineAlias "$site_3_0.lab99" "KillNumberLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab99 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Number of agents to remove per extinction.}
    }
    entry $site_3_0.ent100 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent100" "KillNumberEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab101 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {First Extinction} 
    vTcl:DefineAlias "$site_3_0.lab101" "FirstExtinctionLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab101 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Timestep of the first extinction.}
    }
    entry $site_3_0.ent102 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent102" "FirstExtinctionEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab103 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Extinction Period} 
    vTcl:DefineAlias "$site_3_0.lab103" "ExtinctionPeriodLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab103 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Number of timesteps between extinctions.}
    }
    entry $site_3_0.ent104 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent104" "ExtinctionPeriodEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab105 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Spontaneous Response} 
    vTcl:DefineAlias "$site_3_0.lab105" "SpontaneousRespinseLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab105 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Probability that an agent will act when no task is chosen.}
    }
    entry $site_3_0.ent106 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent106" "SpontaneousResponseEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab108 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Advanced 
    vTcl:DefineAlias "$site_3_0.lab108" "AdvancedLabel" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab109 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 17 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Core 
    vTcl:DefineAlias "$site_3_0.lab109" "CoreLabel" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab110 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Hetero Range Max} 
    vTcl:DefineAlias "$site_3_0.lab110" "HeteroRangeMaxLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab110 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Spontaneous Response Probability}
    }
    entry $site_3_0.ent112 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent112" "HeteroRangeMaxEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab113 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Hetero Range Min} 
    vTcl:DefineAlias "$site_3_0.lab113" "HeteroRangeMinLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab113 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Spontaneous Response Probability}
    }
    entry $site_3_0.ent116 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent116" "HeteroRangeMinEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab117 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Hetero Radius Max} 
    vTcl:DefineAlias "$site_3_0.lab117" "HeteroRadiusMaxLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab117 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Spontaneous Response Probability}
    }
    entry $site_3_0.ent118 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent118" "HeteroRadiusMaxEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab119 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Hetero Radius Min} 
    vTcl:DefineAlias "$site_3_0.lab119" "HeteroRadiusMinLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab119 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Spontaneous Response Probability}
    }
    entry $site_3_0.ent120 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent120" "HeteroRadiusMinEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab121 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {RP Gaussian MU} 
    vTcl:DefineAlias "$site_3_0.lab121" "GaussianMuLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab121 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Spontaneous Response Probability}
    }
    entry $site_3_0.ent122 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent122" "GaussianMuEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab123 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {RP Gaussian STD} 
    vTcl:DefineAlias "$site_3_0.lab123" "GaussianStdLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab123 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Spontaneous Response Probability}
    }
    entry $site_3_0.ent124 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent124" "GaussianStdEntry" vTcl:WidgetProc "Window" 1
    ttk::combobox $site_3_0.tCo125 \
        -values {0 1 2 {} {} {} {}} \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -textvariable combobox -foreground {} -background #f2b83d \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo125" "ThreshDyInitEntry" vTcl:WidgetProc "Window" 1
    ttk::combobox $site_3_0.tCo126 \
        -values {0 1 2 3 {} {} {} {}} \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -textvariable combobox -foreground {} -background #f2b83d \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo126" "ThreshDynamicEntry" vTcl:WidgetProc "Window" 1
    label $site_3_0.lab127 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #000000 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 13 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #f2b83d -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Range 
    vTcl:DefineAlias "$site_3_0.lab127" "RangeLabel" vTcl:WidgetProc "Window" 1
    bind $site_3_0.lab127 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Range of threshold values after scaling.}
    }
    entry $site_3_0.ent128 \
        -background #f2b83d -disabledforeground #a3a3a3 \
        -font {-family Arial -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$site_3_0.ent128" "RangeEntry" vTcl:WidgetProc "Window" 1
    button $site_3_0.but130 \
        -activebackground #f2b83d -activeforeground #000000 \
        -background #f2b83d -command Help -compound center \
        -disabledforeground #a3a3a3 \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Help 
    vTcl:DefineAlias "$site_3_0.but130" "HelpButton" vTcl:WidgetProc "Window" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.398 -y 0 -rely 0.076 -width 0 \
        -relwidth 0.203 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.822 -width 107 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.211 -y 0 -rely 0.822 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.68 -y 0 -rely 0.015 -width 0 \
        -relwidth 0.222 -height 0 -relheight 0.091 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 0 -relx 0.906 -y 0 -rely 0.015 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.068 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.32 -width 0 -relwidth 0.07 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.624 -width 0 \
        -relwidth 0.102 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.7 -width 0 \
        -relwidth 0.127 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.776 -width 0 \
        -relwidth 0.102 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.852 -width 0 \
        -relwidth 0.109 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.548 -width 0 \
        -relwidth 0.109 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.624 -width 0 \
        -relwidth 0.109 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent76 \
        -in $site_3_0 -x 0 -relx 0.227 -y 0 -rely 0.244 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent80 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.776 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent81 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.852 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent82 \
        -in $site_3_0 -x 0 -relx 0.227 -y 0 -rely 0.548 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent83 \
        -in $site_3_0 -x 0 -relx 0.227 -y 0 -rely 0.624 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo86 \
        -in $site_3_0 -x 0 -relx 0.227 -y 0 -rely 0.396 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent87 \
        -in $site_3_0 -x 0 -relx 0.227 -y 0 -rely 0.32 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.396 -width 0 \
        -relwidth 0.102 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab89 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.116 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo90 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab91 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.32 -width 0 \
        -relwidth 0.07 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent92 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.32 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.396 -width 0 \
        -relwidth 0.085 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent94 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.396 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab95 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.472 -width 0 \
        -relwidth 0.07 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent96 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.472 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab97 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.548 -width 0 \
        -relwidth 0.085 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent98 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.548 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab99 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.7 -width 0 -relwidth 0.08 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $site_3_0.ent100 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.7 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab101 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.776 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent102 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.776 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab103 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.852 -width 0 \
        -relwidth 0.102 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent104 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.852 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab105 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.7 -width 0 -relwidth 0.143 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $site_3_0.ent106 \
        -in $site_3_0 -x 0 -relx 0.227 -y 0 -rely 0.7 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab108 \
        -in $site_3_0 -x 0 -relx 0.391 -y 0 -rely 0.183 -width 0 \
        -relwidth 0.088 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab109 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.183 -width 0 \
        -relwidth 0.048 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab110 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.12 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent112 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.244 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab113 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.32 -width 0 \
        -relwidth 0.113 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent116 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.32 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab117 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.396 -width 0 \
        -relwidth 0.12 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent118 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.396 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab119 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.472 -width 0 \
        -relwidth 0.12 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent120 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.472 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab121 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.548 -width 0 \
        -relwidth 0.12 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent122 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.548 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab123 \
        -in $site_3_0 -x 0 -relx 0.695 -y 0 -rely 0.624 -width 0 \
        -relwidth 0.12 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent124 \
        -in $site_3_0 -x 0 -relx 0.867 -y 0 -rely 0.624 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo125 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.7 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo126 \
        -in $site_3_0 -x 0 -relx 0.539 -y 0 -rely 0.624 -width 0 \
        -relwidth 0.066 -height 0 -relheight 0.032 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab127 \
        -in $site_3_0 -x 0 -relx 0.07 -y 0 -rely 0.472 -width 0 \
        -relwidth 0.055 -height 0 -relheight 0.047 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent128 \
        -in $site_3_0 -x 0 -relx 0.227 -y 0 -rely 0.472 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but130 \
        -in $site_3_0 -x 0 -relx 0.906 -y 0 -rely 0.107 -width 107 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

