#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Oct 01, 2022 05:18:31 PM CDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import errorPopup


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    error_list = ["Error 1", "Error 2", "Error 3", "Error 1", "Error 2", "Error 3", "Error 1", "Error 2", "Error 3",
                  "Error 1", "Error 2", "Error 3"]
    _w1 = errorPopup.ErrorGui(_top1, error_list=error_list, title="Error")
    root.mainloop()


if __name__ == '__main__':
    main()




