#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 14, 2022 05:03:21 PM CDT  platform: Windows NT

import tkinter as tk
from src.GUI import statSwarm


def main(*args):
    """Main entry point for the application."""
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = statSwarm.SwarmGui(_top1)
    root.mainloop()


if __name__ == '__main__':
    main()
