#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Aug 03, 2022 07:05:08 PM CDT  platform: Windows NT

import tkinter as tk
from src.GUI import statDemand


def main(*args):
    """Main entry point for the application."""
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global top, _w1
    top = root
    top.protocol('WM_DELETE_WINDOW', top.destroy)
    top.geometry("1280x657+-8+-8")
    top.minsize(120, 120)
    top.resizable(True, True)
    top.title("STAT")
    top.configure(background="#000000")
    top.configure(highlightbackground="#d9d9d9")
    top.configure(highlightcolor="black")
    _w1 = statDemand.DemandGui(top, 5)
    root.mainloop()


if __name__ == '__main__':
    main()
